[project]
name = "chromadb_etl"
version = "0.1"
dependencies = [
   "PyPDF2==3.0.1",
   "retry==0.9.2",
   "langchain_community==0.0.34",
   "langchain==0.1.16",
   "unstructured==0.11.8",
   "chromadb==0.5.0",
   "ollama==0.1.9"
]

[project.optional-dependencies]
dev = ["black", "flake8"]